project:
  type: website
  output-dir: docs

website:
  title: "Eason' Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - thanks.qmd

format:
  html:
    theme: morph
    css: styles.css
    toc: true



